Repository jeremylvln/Shulker, pull requests merged in 2024-08, with the labels that each got.

#616 docs: add search
  docs/src/.vitepress/config.mts
Labels: type:documentation :books:, good first issue

#623 feat(shulker-crds): specify scale subresource for ProxyFleet and MinecraftServerFleet
  kube/helm/templates/crds/shulkermc.io_minecraftserverfleets.yaml
  kube/helm/templates/crds/shulkermc.io_proxyfleets.yaml
  packages/shulker-crds/src/v1alpha1/minecraft_server_fleet.rs
  packages/shulker-crds/src/v1alpha1/proxy_fleet.rs
  packages/shulker-utils/src/time.rs
Labels: type:enhancement :rocket:

#627 fix(shulker-proxy-agent): crash when LoadBalancer service does not have any ingress in status
  packages/shulker-operator/src/reconcilers/minecraft_cluster/proxy_role.rs
  packages/shulker-operator/src/reconcilers/minecraft_cluster/snapshots/shulker_operator__reconcilers__minecraft_cluster__proxy_role__tests__build_snapshot.snap
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/kubernetes/ImplKubernetesGatewayAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/kubernetes/KubernetesGatewayAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/services/PlayerMovementService.kt
Labels: type:bug :bug:, priority:critical :fire_engine:

#629 feat(shulker-proxy-agent): expose player teleporting in API
  packages/shulker-proxy-agent/src/bungeecord/kotlin/io/shulkermc/proxyagent/bungeecord/ProxyInterfaceBungeeCord.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/ProxyInterface.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/pubsub/PubSubAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/pubsub/RedisPubSubAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/api/ShulkerProxyAPIImpl.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/commands/CommandHandlerHelper.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/commands/FindCommandHandler.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/commands/TeleportCommandHandler.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/handlers/TeleportPlayerOnServerHandler.kt
  packages/shulker-proxy-agent/src/velocity/kotlin/io/shulkermc/proxyagent/velocity/ProxyInterfaceVelocity.kt
  packages/shulker-proxy-api/src/main/java/io/shulkermc/proxyagent/api/ShulkerProxyAPI.java
Labels: type:enhancement :rocket:

#631 feat: support providing external servers
  kube/helm/templates/crds/shulkermc.io_minecraftclusters.yaml
  packages/shulker-crds/src/v1alpha1/minecraft_cluster.rs
  packages/shulker-operator/src/reconcilers/minecraft_cluster/external_servers_config_map.rs
  packages/shulker-operator/src/reconcilers/minecraft_cluster/fixtures.rs
  packages/shulker-operator/src/reconcilers/minecraft_cluster/mod.rs
  packages/shulker-operator/src/reconcilers/minecraft_cluster/snapshots/shulker_operator__reconcilers__minecraft_cluster__external_servers_config_map__tests__build_snapshot.snap
  packages/shulker-operator/src/reconcilers/proxy_fleet/fleet.rs
  packages/shulker-operator/src/reconcilers/proxy_fleet/snapshots/shulker_operator__reconcilers__proxy_fleet__fleet__tests__build_snapshot.snap
  packages/shulker-proxy-agent/build.gradle.kts
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/filesystem/FileSystemAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/filesystem/LocalFileSystemAdapter.kt
  packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/services/ServerDirectoryService.kt
  settings.gradle.kts
Labels: type:enhancement :rocket:

#634 feat: add first-party support for Minestom servers
  Cargo.lock
  build.gradle.kts
  kube/helm/templates/crds/shulkermc.io_minecraftserverfleets.yaml
  kube/helm/templates/crds/shulkermc.io_minecraftservers.yaml
  packages/shulker-crds/src/v1alpha1/minecraft_server.rs
  packages/shulker-kube-utils/src/reconcilers/mod.rs
  packages/shulker-operator/assets/server-init-fs.sh
  packages/shulker-operator/src/reconcilers/minecraft_server/gameserver.rs
  packages/shulker-operator/src/reconcilers/minecraft_server/snapshots/shulker_operator__reconcilers__minecraft_server__config_map__tests__build_snapshot.snap
  packages/shulker-operator/src/reconcilers/minecraft_server_fleet/snapshots/shulker_operator__reconcilers__minecraft_server_fleet__config_map__tests__build_snapshot.snap
  packages/shulker-server-agent/src/minestom/kotlin/io/shulkermc/serveragent/paper/ServerInterfaceMinestom.kt
  packages/shulker-server-agent/src/minestom/kotlin/io/shulkermc/serveragent/paper/ShulkerServerAgentMinestom.kt
  packages/shulker-server-agent/src/minestom/kotlin/io/shulkermc/serveragent/paper/config/PaperConfiguration.kt
  packages/shulker-server-agent/src/minestom/kotlin/io/shulkermc/serveragent/paper/config/ServerProperties.kt
  settings.gradle.kts
Labels: type:enhancement :rocket:
